### ISSUE TITLE
/api/me endpoint JSON response discrepancy 

### ISSUE THREAD

**Issue by Talamantez** [canopy-project/canopy-project#16]
API documentation specifies the second key in the JSON response for GET /api/me as  "validated".
The actual response that I'm seeing uses "activated" instead of "validated". Tests using "activated" are passing.

{
    "result" : "ok",
    "validated" : <VALIDATED>,
    "username" : <USERNAME>,
    "email" : <EMAIL>,
}

I'm assuming this has just been updated, but I thought I'd note the discrepancy.
Thanks!

**Comment by gregulator** [comment]
Fixed with canopy-project/canopy-server@92216f5037a313f37788fa6d98c7e4c21bba67fe
