### ISSUE TITLE
Create user with email that is too short does not fail

### ISSUE THREAD

**Issue by Talamantez** [canopy-project/canopy-project#23]
Expect to fail with 500, but returns 200

** FAIL TEST: REGISTER WITH TOO SHORT EMAIL ** *** REGISTERING USER user11003231 
	[ POST https://dev02.canopy.link/api/create_user ]
   Message:
     Expected 200 to equal 500.

**Comment by gregulator** [comment]
Fixed with canopy-project/canopy-server@a6da7cf5d92d6f1dea5217a18087e4517e0999c4
