### ISSUE TITLE
Create user with username that begins with number does not fail

### ISSUE THREAD

**Issue by Talamantez** [canopy-project/canopy-project#24]
Expect to fail with 500, returns 200

** FAIL TEST: REGISTER USER WITH USERNAME THAT STARTS WITH NUMBER ** 
	[ POST https://dev02.canopy.link/api/create_user ]
   Message:
     Expected 200 to equal 500.

**Comment by gregulator** [comment]
Registering user with username that starts with number returns the expected error for me.  Maybe it was fixed or maybe a problem with the test.  Closing.
